// <auto-generated />
namespace EventsManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddingUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201407010624103_AddingUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
